### ISSUE TITLE
I get an error when I click on dashboard 

### ISSUE THREAD

**Issue by harigist** [dkmstr/openuds#28] opened 2018-11-13 11:05 UTC
Hi @dkmstr ,

I have successfully installed the openuds, thanks.

but when I click on dashboard (overview) page, I get the below error **In UI** 

NOTE : Other funationalties of creating service, service pools everything works :+1: 

![overview](https://user-images.githubusercontent.com/35326779/48409494-fe5aaf00-e761-11e8-955b-e7ff3ee4da05.png)

**In log file,** 

==> uds.log <==
ERROR 2018-11-13 12:01:00,972 system getServicesPoolsCounters 82 exception
Traceback (most recent call last):
  File "/home/hari/openuds/testuds-master/server/src/uds/REST/methods/system.py", line 71, in getServicesPoolsCounters
    for x in counters.getCounters(us, counter_type, since=since, to=to, limit=POINTS, use_max=USE_MAX, all=complete):
  File "/home/hari/openuds/testuds-master/server/src/uds/core/util/stats/counters.py", line 113, in getCounters
    for i in statsManager().getCounters(__transDict[type(obj)], counterType, owner_ids, since, to, limit, use_max):
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/models/query.py", line 1225, in __iter__
    query = iter(self.query)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/models/sql/query.py", line 79, in __iter__
    self._execute_query()
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/models/sql/query.py", line 113, in _execute_query
    self.cursor.execute(self.sql, params)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1055, "Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'uds.uds_stats_c.stamp' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
ERROR 2018-11-13 12:01:00,972 system getServicesPoolsCounters 82 exception
Traceback (most recent call last):
  File "/home/hari/openuds/testuds-master/server/src/uds/REST/methods/system.py", line 71, in getServicesPoolsCounters
    for x in counters.getCounters(us, counter_type, since=since, to=to, limit=POINTS, use_max=USE_MAX, all=complete):
  File "/home/hari/openuds/testuds-master/server/src/uds/core/util/stats/counters.py", line 113, in getCounters
    for i in statsManager().getCounters(__transDict[type(obj)], counterType, owner_ids, since, to, limit, use_max):
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/models/query.py", line 1225, in __iter__
    query = iter(self.query)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/models/sql/query.py", line 79, in __iter__
    self._execute_query()
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/models/sql/query.py", line 113, in _execute_query
    self.cursor.execute(self.sql, params)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/hari/openuds/testuds-master/Python-2.7.14/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1055, "Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'uds.uds_stats_c.stamp' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
DEBUG 2018-11-13 12:01:00,974 request process_response 77 Deleting 140061811316480
DEBUG 2018-11-13 12:01:00,974 request process_response 77 Deleting 140061383300864

**Comment by dkmstr** [comment] 2018-11-13 11:19
That is a problem caused by your Mysql configuration. This will be fixed on next (3.0) release, but right now, you must follow this on the MYSQL server to solve the issue :)
https://stackoverflow.com/questions/23921117/disable-only-full-group-by

**Closed by dkmstr** 2018-11-13 11:19 UTC
